### ISSUE TITLE
Cannot connect to localhost:9200

### ISSUE THREAD

**Issue by chadwilken** [getong/elasticsearch-action#1]
I'm trying to use this to run specs but I keep getting that it can't connect to `localhost:9200`. Do you know if there is a workaround or username/password combo that I need to use?

**Comment by getong** [comment]
I am sorry, I test it in travis ci and circle ci, but I do not test it in github action.
It seems that the github action does not support the elasticsearch:
https://github.com/getong/elasticsearch-action/blob/52654b0d89132b1635f989d3ba639623dcc87ebc/.github/workflows/elasticsearch_ci.yml#L23-L28

This command tests ok in my own machine, but github action does not.

**Comment by getong** [comment]
```
- name: Configure sysctl limits
  run: |
    sudo swapoff -a
    sudo sysctl -w vm.swappiness=1
    sudo sysctl -w fs.file-max=262144
    sudo sysctl -w vm.max_map_count=262144

- name: Runs Elasticsearch
  uses: elastic/elastic-github-actions/elasticsearch@master
  with:
    stack-version: 7.6.1
```
You can change to use elastic/elastic-github-actions/elasticsearch

**Comment by getong** [comment]
```
steps:
- name: Configure sysctl limits
  run: |
    sudo swapoff -a
    sudo sysctl -w vm.swappiness=1
    sudo sysctl -w fs.file-max=262144
    sudo sysctl -w vm.max_map_count=262144

- uses: getong/elasticsearch-action@v1.2
  with:
    elasticsearch version: '7.6.1'
    host port: 9200
    container port: 9200
    host node port: 9300
    node port: 9300
    discovery type: 'single-node'
```
You can use v1.2
